# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: David Sanchez-Charles
email: dscharles@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hey! Check this awesemo website if you want to know more about me and 
  the cool stuff I do as an IT researcher.
baseurl: "" # the subpath of your site, e.g. /blog
lang: "es"
url: "https://dscharles.github.io" # the base hostname & protocol for your site
twitter_username: dscharles
github_username:  dscharles
disqus_username:

# Build settings
markdown: kramdown
relative_permalinks: false
permalink: /:categories/:title/
# permalink: /blog/:year/:month/:day/:title


# Posts settings
future: true
safe: false
lsi: false
excerpt_separator: "\n\n"

# Other collections besides posts
collections: 
  - news
  publications: 
    output: true
    permalink: /publication/:title


compress_html:
  comments: ["<!-- ", " -->"]
  clippings: all
  endings: all


sass:
  sass_dir: assets/_sass


images: '/assets/images'
